CREATE INDEX "idx_learning_metrics_user_id" ON "learning_metrics" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_learning_metrics_material_id" ON "learning_metrics" USING btree ("material_id");--> statement-breakpoint
CREATE INDEX "idx_learning_metrics_last_practiced" ON "learning_metrics" USING btree ("last_practiced_at");--> statement-breakpoint
CREATE INDEX "idx_learning_metrics_user_material" ON "learning_metrics" USING btree ("user_id","material_id");--> statement-breakpoint
CREATE INDEX "idx_lesson_slots_mentor_id" ON "lesson_slots" USING btree ("mentor_id");--> statement-breakpoint
CREATE INDEX "idx_lesson_slots_start_time" ON "lesson_slots" USING btree ("start_time");--> statement-breakpoint
CREATE INDEX "idx_lesson_slots_status" ON "lesson_slots" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_lesson_slots_mentor_start" ON "lesson_slots" USING btree ("mentor_id","start_time");--> statement-breakpoint
CREATE INDEX "idx_materials_creator_id" ON "materials" USING btree ("creator_id");--> statement-breakpoint
CREATE INDEX "idx_materials_type" ON "materials" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_materials_difficulty" ON "materials" USING btree ("difficulty");--> statement-breakpoint
CREATE INDEX "idx_materials_is_public" ON "materials" USING btree ("is_public");--> statement-breakpoint
CREATE INDEX "idx_materials_quality_status" ON "materials" USING btree ("quality_status");--> statement-breakpoint
CREATE INDEX "idx_materials_creator_type" ON "materials" USING btree ("creator_id","type");--> statement-breakpoint
CREATE INDEX "idx_messages_sender_id" ON "messages" USING btree ("sender_id");--> statement-breakpoint
CREATE INDEX "idx_messages_receiver_id" ON "messages" USING btree ("receiver_id");--> statement-breakpoint
CREATE INDEX "idx_messages_reservation_id" ON "messages" USING btree ("reservation_id");--> statement-breakpoint
CREATE INDEX "idx_messages_created_at" ON "messages" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "idx_reservations_slot_id" ON "reservations" USING btree ("slot_id");--> statement-breakpoint
CREATE INDEX "idx_reservations_student_id" ON "reservations" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "idx_reservations_mentor_id" ON "reservations" USING btree ("mentor_id");--> statement-breakpoint
CREATE INDEX "idx_reservations_status" ON "reservations" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_reservations_payment_status" ON "reservations" USING btree ("payment_status");--> statement-breakpoint
CREATE INDEX "idx_reservations_student_status" ON "reservations" USING btree ("student_id","status");--> statement-breakpoint
CREATE INDEX "idx_subscriptions_user_id" ON "subscriptions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_subscriptions_status" ON "subscriptions" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_subscriptions_stripe_subscription_id" ON "subscriptions" USING btree ("stripe_subscription_id");--> statement-breakpoint
CREATE INDEX "idx_subscriptions_user_status" ON "subscriptions" USING btree ("user_id","status");--> statement-breakpoint
CREATE INDEX "idx_users_clerk_id" ON "users" USING btree ("clerk_id");--> statement-breakpoint
CREATE INDEX "idx_users_email" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "idx_users_role" ON "users" USING btree ("role");--> statement-breakpoint
CREATE INDEX "idx_webhook_events_event_id" ON "webhook_events" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "idx_webhook_events_source" ON "webhook_events" USING btree ("source");--> statement-breakpoint
CREATE INDEX "idx_webhook_events_type" ON "webhook_events" USING btree ("type");--> statement-breakpoint
CREATE INDEX "idx_webhook_events_created_at" ON "webhook_events" USING btree ("created_at");