/**
 * MUEDnote API Types
 * サーバーAPIとの通信で使用する型定義
 */

// ========================================
// Fragment (思考ログ)
// ========================================

export type FragmentStatus = 'pending' | 'processing' | 'completed' | 'failed' | 'archived';
export type FragmentImportance = 'low' | 'medium' | 'high' | 'critical';

export interface Fragment {
  id: string;
  user_id: string;
  content: string;
  project_id: string | null;
  importance: FragmentImportance;
  status: FragmentStatus;
  captured_at: string;
  created_at: string;
  updated_at: string;
  archived_at: string | null;
  // HLA分析結果
  action_items?: ActionItem[];
  emotions?: EmotionData;
  tags?: Tag[];
  projectName?: string;
  projectColor?: string;
}

export interface ActionItem {
  category: string;
  content: string;
  priority?: string;
}

export interface EmotionData {
  mood: 'creative' | 'frustrated' | 'mixed' | 'neutral';
  confidence: number;
}

export interface Tag {
  id: string;
  name: string;
  color: string;
  confidence?: number;
  isAutoGenerated?: boolean;
}

// ========================================
// Session
// ========================================

export type SessionType = 'production' | 'practice' | 'learning' | 'other';
export type SessionStatus = 'draft' | 'active' | 'completed' | 'archived';

export interface Session {
  id: string;
  user_id: string;
  type: SessionType;
  title: string;
  user_short_note: string;
  project_id?: string;
  project_name?: string;
  daw_meta?: DAWMetadata;
  ai_annotations?: AIAnnotations;
  is_public: boolean;
  share_with_mentor: boolean;
  status: SessionStatus;
  created_at: string;
  updated_at: string;
}

export interface DAWMetadata {
  dawName?: string;
  projectName?: string;
  bpm?: number;
  key?: string;
  timeSignature?: string;
}

export interface AIAnnotations {
  focusArea: string;
  intentHypothesis: string;
  confidence: number;
  analysisMethod: string;
}

// ========================================
// API Request/Response Types
// ========================================

// Fragment
export interface CreateFragmentRequest {
  content: string;
  projectId?: string;
  importance?: FragmentImportance;
}

export interface UpdateFragmentRequest {
  id: string;
  content?: string;
  projectId?: string | null;
  importance?: FragmentImportance;
  status?: FragmentStatus;
}

export interface FragmentListResponse {
  fragments: Fragment[];
  pagination: PaginationInfo;
}

// Session
export interface CreateSessionRequest {
  type: SessionType;
  title: string;
  userShortNote: string;
  projectId?: string;
  projectName?: string;
  dawMeta?: DAWMetadata;
  isPublic?: boolean;
  shareWithMentor?: boolean;
}

export interface SessionListResponse {
  sessions: Session[];
  pagination: PaginationInfo;
}

// Common
export interface PaginationInfo {
  total: number;
  limit: number;
  offset: number;
  hasMore: boolean;
}

export interface ApiError {
  error: string;
  details?: string;
}

// ========================================
// Local State Types (for Zustand)
// ========================================

export interface LocalLog {
  id: string;
  timestamp_sec: number;
  text: string;
  confidence?: number;
  created_at: string;
}

export interface LocalSession {
  id: string;
  duration_sec: number;
  started_at: string;
  ended_at?: string;
  status: 'active' | 'completed' | 'synced';
  memo?: string;
  logs: LocalLog[];
}

// ========================================
// v7 MVP Mobile Types
// ========================================

export type MobileSessionStatus = 'active' | 'completed' | 'synced';

export interface MobileSession {
  id: string;
  user_id?: string;
  duration_sec: number;
  started_at: string;
  ended_at: string | null;
  session_memo: string | null;
  status: MobileSessionStatus;
  log_count?: number;
  created_at: string;
}

export interface CreateMobileSessionRequest {
  duration_sec: number;
  started_at: string;       // ISO8601
  ended_at?: string;        // ISO8601
  session_memo?: string;
  device_id?: string;
}

export interface MobileSessionListResponse {
  sessions: MobileSession[];
  pagination: PaginationInfo;
}

export interface MobileLog {
  id: string;
  session_id: string;
  timestamp_sec: number;
  text: string;
  confidence: number | null;
  created_at: string;
}

export interface SaveLogsRequest {
  session_id: string;
  logs: Array<{
    timestamp_sec: number;
    text: string;
    confidence?: number;
  }>;
}

export interface SaveLogsResponse {
  success: boolean;
  saved_count: number;
  session_id: string;
}

export interface SessionLogsResponse {
  session: MobileSession;
  logs: MobileLog[];
}
